# -*- coding: utf-8 -*-
"""Eular project soloutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GX1LTXU5UBkCQ6NCCoCZNuUHbnaxRAc3
"""

import numpy as np

#My verification question, Problem zero, which asks what the sum of all the odd powers belo 620,000 are.
def prop_zero(n):
  start = 1
  x = 0
  while start != n:
    if start % 2 != 0:
      x = start**2 + x
      start = start + 1
    else: start = start + 1
  return x

print(prop_zero(620000))

#This one asks us the sum of all numbers below 1000 that are divisble by 3 or 5.

def divisbleby3and5(n):
  start = 0
  while n != 0:
    if n % 5 == 0 or n % 3 == 0:
      start = start + n
      n = n -1
    else:
      n = n - 1

  return start

print(divisbleby3and5(999))

#this is the even sum of values of the fibbanachi sequence with a value below 4 million

def fib(n):
 if n <=1:
  return n
 else:
  return fib(n - 1) + fib(n - 2)

def evenfib():
  start = 1
  acc = 0

  while start < 34:
    if fib(start) % 2 == 0:
      acc += fib(start)
      start += 1
    else:
      start += 1;

  return acc



print(evenfib())

#Largest Prime Factor

def isprime(n):
  for i in range(1, n):
    if n % i == 0 and

#Lexicographic Permutations Problem 24